{% set name = "eko" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c102f0dc3d14db364e3f454e1ea89923b2dc470289143e20fddcec7cf571b72

build:
  entry_points:
    - ekonav = ekomark.navigator:launch_navigator
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8,<3.11
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8,<3.11
    - scipy >=1.10.1,<2
    - numba >=0.57,<0.58
    - pyyaml =6
    - numpy >=1.24,<2
    - lz4 >=4.0.2,<5

test:
  imports:
    - eko
    - ekobox
    - ekomark
  requires:
    - pip
  commands:
    - pip check
    - ekonav --help

about:
  home: https://eko.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Evolution Kernel Operators: EKO is a Python module to solve the DGLAP equations in N-space in terms of Evolution Kernel Operators in x-space.'
  dev_url: https://github.com/N3PDF/eko

extra:
  recipe-maintainers:
    - scarlehoff
