{% set name = "eko" %}
{% set version = "0.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d7242ec4b32d0cb86fdc75dfabc4434fffbe14d3c26343016d51dc8ac33331c

build:
  entry_points:
    - ekonav = ekomark.navigator:launch_navigator
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9,<3.13
    - scipy >=1.10.1,<2
    - numba >=0.59
    - pyyaml =6
    - numpy >=1.24,<2
    - lz4 >=4.0.2,<5

test:
  imports:
    - eko
    - ekobox
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://eko.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Evolution Kernel Operators: EKO is a Python module to solve the DGLAP equations in N-space in terms of Evolution Kernel Operators in x-space.'
  dev_url: https://github.com/N3PDF/eko

extra:
  recipe-maintainers:
    - scarlehoff
