{% set name = "eko" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c5829baefe88c8e1424a1ec963c0cfde4dc1a6abfa439db2a1a4aca9794ba8d

build:
  entry_points:
    - ekonav = ekomark.navigator:launch_navigator
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<3.13
    - scipy >=1.10.1,<2
    - numba >=0.59
    - pyyaml =6
    - numpy >=1.24,<2
    - lz4 >=4.0.2,<5

test:
  imports:
    - eko
    - ekobox
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://eko.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Evolution Kernel Operators: EKO is a Python module to solve the DGLAP equations in N-space in terms of Evolution Kernel Operators in x-space.'
  dev_url: https://github.com/N3PDF/eko

extra:
  recipe-maintainers:
    - scarlehoff
