{% set name = "eko" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f962f20f1a5bec25775a7dd8c4432e43986972c5968fda8c1afd5e34fa09fc38

build:
  entry_points:
    - ekonav = ekomark.navigator:launch_navigator
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8,<3.11
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8,<3.11
    - scipy >=1.7.3,<2
    - numba >=0.55,<0.56
    - pyyaml =6
    - numpy >=1.21,<2
    - banana-hep >=0.6.4

test:
  imports:
    - eko
    - ekobox
    - ekomark
  requires:
    - pip
    - lz4 >=3.1.10,<4
  commands:
    - pip check
    - ekonav --help

about:
  home: https://eko.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Evolution Kernel Operators: EKO is a Python module to solve the DGLAP equations in N-space in terms of Evolution Kernel Operators in x-space.'
  dev_url: https://github.com/N3PDF/eko

extra:
  recipe-maintainers:
    - scarlehoff
